### ISSUE TITLE
Problem with mount

### ISSUE THREAD

**Issue by drewrukin** [tombenner/toro#3]
Hi, works perfect so far! 

The only issue is that the UI is not mountable.
I tested it on Rails 4.02 and Rails 4.1:
- added   mount Toro::Monitor::Engine => '/toro' to routes rb.
- get the folowing error: GET http://localhost:3000/toro: No route matches [GET] "/toro"

Here is rake routes   result:
Prefix Verb URI Pattern                   Controller#Action
toro_monitor      /toro                         Toro::Monitor::Engine
upload_processfile GET  /upload/processfile(.:format) upload#getfile
                   POST /upload/processfile(.:format) upload#processfile

Anyway, the software is very useful, I comparied it to 'classic_queue' and 'delayed_job'

**Comment by AndrewR777** [comment]
Here is a very simple project (Rails 4.2) with mount problem: 
https://github.com/AndrewR777/catfood/releases/download/1/ToroTest.zip

**Comment by tombenner** [comment]
This is fixed in 0.2.2 (the `app` directory wasn't being properly included by the gemspec). Thanks for reporting it!
